server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/ttqt_acb_sit_phase6
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=phongro
spring.security.user.password=12012001

