server.port=8082
#spring.datasource.url=jdbc:postgresql://localhost:5432/ttqt_acb_sit_phase6
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/ttqt_acb_sit_phase6
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=phongro
spring.security.user.password=12012001
camunda.url=http://host.docker.internal:30081
gemini.api.key=AIzaSyAI4Zgasl2elXqCKUwbd15AQRPF7dH2uxM
minio.endpoint=http://host.docker.internal:9000
minio.access-key=admin
minio.secret-key=admin123
minio.bucket-name=dms-storage