server.port=8080
#spring.datasource.url=jdbc:postgresql://localhost:5432/ttqt_acb_sit_phase6
spring.datasource.url=jdbc:postgresql://dpg-d9a5imt8nd3s73agpfrg-a:5432/ttqt_acb_sit_phase6
spring.datasource.username=ttqt_acb_sit_phase6_user
spring.datasource.password=7V9uB2UcceJoAruIYXVYAcMAmkQC0mNy
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.security.user.name=phongro
spring.security.user.password=12012001
camunda.url=https://bpmn-rz9o.onrender.com
camunda.bpm.client.base-url=${camunda.url}/engine-rest
gemini.api.key=${API_KEY}
minio.endpoint= http://minio:9000
minio.access-key=admin
minio.secret-key=admin123
minio.bucket-name=dms-storage
ocr.url=http://host.docker.internal:30088

# Spring Mail configurations (Gmail SMTP template)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hongphong.12012001@gmail.com
spring.mail.password=ybbh ifnj cfkq ohpr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Camunda Client configuration for Asynchronous Callback Completion
camunda.bpm.client.worker-id=dms-worker
camunda.bpm.client.subscriptions.sendVerificationEmail.lock-duration=3600000
app.callback-base-url=https://dms-api-b25o.onrender.com